2020-11-28 23:09:59,286--test_login.py--48--ERROR--hanjiping_log--用例登录成功出现错误，错误信息为：0 != 2 within 7 places (2 difference)
2020-11-28 23:09:59,287--test_login.py--49--ERROR--hanjiping_log--0 != 2 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_login.py", line 44, in test_login
    self.assertAlmostEqual(expected['code'],res["code"])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 0 != 2 within 7 places (2 difference)
2020-11-28 23:09:59,516--test_login.py--52--INFO--hanjiping_log--用例运行正常密码错误
2020-11-28 23:09:59,617--test_login.py--52--INFO--hanjiping_log--用例运行正常账号不是标准的手机号
2020-11-28 23:10:00,341--test_register.py--65--ERROR--hanjiping_log--注册成功-带注册名该条测试用例未通过
2020-11-28 23:10:00,341--test_register.py--66--ERROR--hanjiping_log--() is not true
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_register.py", line 56, in test_register
    self.assertTrue(res)
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 705, in assertTrue
    raise self.failureException(msg)
AssertionError: () is not true
2020-11-28 23:10:01,264--test_register.py--65--ERROR--hanjiping_log--成功-不带用户名该条测试用例未通过
2020-11-28 23:10:01,264--test_register.py--66--ERROR--hanjiping_log--() is not true
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_register.py", line 56, in test_register
    self.assertTrue(res)
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 705, in assertTrue
    raise self.failureException(msg)
AssertionError: () is not true
2020-11-28 23:10:01,356--test_register.py--69--INFO--hanjiping_log--不输入手机号该条用例通过
2020-11-28 23:10:01,450--test_register.py--69--INFO--hanjiping_log--手机号长度10位该条用例通过
2020-11-28 23:10:01,546--test_register.py--69--INFO--hanjiping_log--手机号长度12位该条用例通过
2020-11-28 23:10:01,658--test_register.py--69--INFO--hanjiping_log--手机号含有非法字符该条用例通过
2020-11-28 23:10:01,928--test_register.py--69--INFO--hanjiping_log--已注册过的手机号该条用例通过
2020-11-28 23:10:02,257--test_register.py--69--INFO--hanjiping_log--密码7位该条用例通过
2020-11-28 23:10:02,588--test_register.py--69--INFO--hanjiping_log--密码17位该条用例通过
2020-11-28 23:10:02,925--test_register.py--69--INFO--hanjiping_log--不输入密码该条用例通过
2020-11-28 23:10:03,515--test_register.py--65--ERROR--hanjiping_log--注册名11位该条测试用例未通过
2020-11-28 23:10:03,516--test_register.py--66--ERROR--hanjiping_log--2 != 0 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_register.py", line 49, in test_register
    self.assertAlmostEqual(expected['code'],res['code'])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 2 != 0 within 7 places (2 difference)
2020-11-28 23:10:03,847--test_register.py--69--INFO--hanjiping_log--类型输入非0，1内容该条用例通过
